apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: spangre-utsettelser
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  startup:
    failureThreshold: 10
    initialDelay: 20
    path: /isready
    periodSeconds: 5
    port: 8080
    timeout: 1
  liveness:
    failureThreshold: 10
    initialDelay: 20
    path: /isalive
    periodSeconds: 5
    port: 8080
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 1000m
      memory: 512Mi
  parallelism: 24
  azure:
    application:
      enabled: true
      tenant: nav.no
  kafka:
    pool: nav-prod
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spangre-utsettelser-v1
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
