apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: spangre-utsettelser
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  azure:
    application:
      enabled: true
      tenant: nav.no
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spangre-utsettelser-v1
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
