name: Le Build

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: create image tag
      run: echo "IMAGE=docker.pkg.github.com/${{ github.repository }}/spangre-utsettelser:$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '17.x'
    - name: build
      run: ./gradlew build
    - name: build docker image
      run: docker build . --pull -t ${IMAGE}
    - name: push docker image
      run: |
        docker login --username "$GITHUB_REPOSITORY" -p ${{ secrets.GITHUB_TOKEN }} https://docker.pkg.github.com
        docker push ${IMAGE}

  deployProd:
    name: Deploy to prod
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Create image tag
        run: echo "IMAGE=docker.pkg.github.com/${{ github.repository }}/spangre-utsettelser:$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: deploy/prod.yml
